name: deploy

# alle schon laufenden "deploy"s canceln
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  repository_dispatch:
    types:
      - redeploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install
      - run: yarn build

      - run: mv build docs
      - name: git config
        run: |
          git config --global user.email "CI@localhost"
          git config --global user.name "GH Actions CI"
      - name: git commit / push
        run: |
          git add -f docs
          git commit -m "web build: ${{ github.event.commits[0].message }}"
          git push --force origin HEAD:web-build
